<?php

namespace ContainerOYx1nyS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VQxyKVOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vQxyKVO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vQxyKVO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'imageRepository' => ['privates', 'App\\Repository\\ImageRepository', 'getImageRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
            'uploaderHelper' => ['privates', 'App\\Service\\UploaderHelper', 'getUploaderHelperService', true],
            'validator' => ['privates', 'api_platform.validator', 'getApiPlatform_ValidatorService', true],
        ], [
            'entityManager' => '?',
            'imageRepository' => 'App\\Repository\\ImageRepository',
            'security' => '?',
            'uploaderHelper' => 'App\\Service\\UploaderHelper',
            'validator' => '?',
        ]);
    }
}
