<?php

namespace ContainerOYx1nyS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ImageController' shared autowired service.
     *
     * @return \App\Controller\ImageController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ImageController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/SharingToggler.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ThumbnailProvider.php';

        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));
        $b = ($container->privates['App\\Repository\\ImageRepository'] ?? $container->load('getImageRepositoryService'));
        $c = ($container->privates['App\\Service\\UploaderHelper'] ?? $container->load('getUploaderHelperService'));

        $container->services['App\\Controller\\ImageController'] = $instance = new \App\Controller\ImageController($a, $b, $c, ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()), new \App\Service\SharingToggler($b, $a, ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService())), new \App\Service\ThumbnailProvider($b, $a, $c));

        $instance->setContainer(($container->privates['.service_locator.OuIzoRA'] ?? $container->load('get_ServiceLocator_OuIzoRAService'))->withContext('App\\Controller\\ImageController', $container));

        return $instance;
    }
}
