<?php

namespace ContainerDvhDCOy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5QaIM7_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5QaIM7.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5QaIM7.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ImageController::deleteImage' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\ImageController::handleDropzone' => ['privates', '.service_locator.n.32Wpi', 'get_ServiceLocator_N_32WpiService', true],
            'App\\Controller\\ImageController::latestPhotosAjax' => ['privates', '.service_locator.g6H.xPr', 'get_ServiceLocator_G6H_XPrService', true],
            'App\\Controller\\ImageController::makePrivate' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\MainPageController::uploadFileAction' => ['privates', '.service_locator.vQxyKVO', 'get_ServiceLocator_VQxyKVOService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\SecurityController::logout' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.hjqTVeC', 'get_ServiceLocator_HjqTVeCService', true],
            'App\\Controller\\SecurityController::update' => ['privates', '.service_locator.vogmsH7', 'get_ServiceLocator_VogmsH7Service', true],
            'App\\Controller\\TagController::addTag' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\ImageController:deleteImage' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\ImageController:handleDropzone' => ['privates', '.service_locator.n.32Wpi', 'get_ServiceLocator_N_32WpiService', true],
            'App\\Controller\\ImageController:latestPhotosAjax' => ['privates', '.service_locator.g6H.xPr', 'get_ServiceLocator_G6H_XPrService', true],
            'App\\Controller\\ImageController:makePrivate' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\MainPageController:uploadFileAction' => ['privates', '.service_locator.vQxyKVO', 'get_ServiceLocator_VQxyKVOService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\SecurityController:logout' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.hjqTVeC', 'get_ServiceLocator_HjqTVeCService', true],
            'App\\Controller\\SecurityController:update' => ['privates', '.service_locator.vogmsH7', 'get_ServiceLocator_VogmsH7Service', true],
            'App\\Controller\\TagController:addTag' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\ImageController::deleteImage' => '?',
            'App\\Controller\\ImageController::handleDropzone' => '?',
            'App\\Controller\\ImageController::latestPhotosAjax' => '?',
            'App\\Controller\\ImageController::makePrivate' => '?',
            'App\\Controller\\MainPageController::uploadFileAction' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::logout' => '?',
            'App\\Controller\\SecurityController::register' => '?',
            'App\\Controller\\SecurityController::update' => '?',
            'App\\Controller\\TagController::addTag' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ImageController:deleteImage' => '?',
            'App\\Controller\\ImageController:handleDropzone' => '?',
            'App\\Controller\\ImageController:latestPhotosAjax' => '?',
            'App\\Controller\\ImageController:makePrivate' => '?',
            'App\\Controller\\MainPageController:uploadFileAction' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:logout' => '?',
            'App\\Controller\\SecurityController:register' => '?',
            'App\\Controller\\SecurityController:update' => '?',
            'App\\Controller\\TagController:addTag' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
