<?php

namespace ContainerDvhDCOy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormRegisterUserTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\FormRegisterUserType' shared autowired service.
     *
     * @return \App\Form\FormRegisterUserType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/FormRegisterUserType.php';

        return $container->privates['App\\Form\\FormRegisterUserType'] = new \App\Form\FormRegisterUserType();
    }
}
