<?php

namespace ContainerDvhDCOy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLiipImagine_Binary_Loader_FlysystemLoaderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'liip_imagine.binary.loader.flysystem_loader' shared service.
     *
     * @return \Liip\ImagineBundle\Binary\Loader\FlysystemLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/liip/imagine-bundle/Binary/Loader/LoaderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/liip/imagine-bundle/Binary/Loader/FlysystemLoader.php';

        return $container->services['liip_imagine.binary.loader.flysystem_loader'] = new \Liip\ImagineBundle\Binary\Loader\FlysystemLoader(\Symfony\Component\Mime\MimeTypes::getDefault(), ($container->services['oneup_flysystem.default_filesystem_filesystem'] ?? $container->getOneupFlysystem_DefaultFilesystemFilesystemService()));
    }
}
