<?php

namespace ContainerDvhDCOy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOneupFlysystem_MountManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'oneup_flysystem.mount_manager' shared service.
     *
     * @return \League\Flysystem\MountManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/league/flysystem/src/MountManager.php';

        return $container->services['oneup_flysystem.mount_manager'] = new \League\Flysystem\MountManager();
    }
}
