<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUxkHoce\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUxkHoce/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUxkHoce.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUxkHoce\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUxkHoce\App_KernelDevDebugContainer([
    'container.build_hash' => 'UxkHoce',
    'container.build_id' => '2443b016',
    'container.build_time' => 1617132094,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUxkHoce');
