<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAHGWnM7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAHGWnM7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAHGWnM7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAHGWnM7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAHGWnM7\App_KernelDevDebugContainer([
    'container.build_hash' => 'AHGWnM7',
    'container.build_id' => 'b01a0023',
    'container.build_time' => 1616620987,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAHGWnM7');
